### PR TITLE
Spelling fixes

### PR DESCRIPTION
**Pull request by mikedld**
Decided not to fix "teamcilty" as not sure whether it will result in preferences loss.

### CODE REVIEW

**Comment by VladRassokhin** [comment]
Your changes are safe since they doesn't modify string literals in `UpdateChangesConstants.java`

**Comment by mikedld** [comment]
@VladRassokhin, do you mean present changes only, or are you saying that fixing the "teamcilty" is safe as well? I figured the latter might affect some kind of scope in which plugin preferences are being stored; if that's not the case I'll add one more commit to this PR.

**Comment by VladRassokhin** [comment]
I mean exactly this pull-request with current commits.
'teamcity' changes are not safe.

7 авг. 2016 г. 13:34 пользователь "Mike Gelfand" <notifications@github.com>
написал:

**Comment by mikedld** [comment]
Okay, leaving "teamcilty" fix to someone more involved ;)

**Comment by VladRassokhin** [comment]
Honestly, I think changes in constants would never be accepted since it requires converter or supporting  both constans at the same time, also any edit of build feature would cause changes since literals would be updated.
Also there's [bundled (since 10.0) plugin](https://github.com/JetBrains/commit-status-publisher) which provides same or similar functionality, has oauth support and other features. 
So IMHO, pragmatic approach would be not invest much time into this plugin, especially if it not add any features or fixes some bugs.

**Comment by mikedld** [comment]
@VladRassokhin, main show-stopper for me with the built-in plugin is that it provides less flexibility than this one. Specifically, I'm making use of possibility to specify custom context and, as of couple days ago, possibility to specify custom description (based on https://github.com/mshish/TeamCity.GitHub/commit/0464da1bafdc184f34ddc94af141bb1aeed7e939 which I adjusted a bit to customize as in "Finished <custom text here>: ..." and also extended the approach to "Started <custom text here>" where both custom texts are the same preference field).

**Pull request closed without merging**
