### PR TITLE
Add a failure status condition and report

### LINKED ISSUE #77: Report tests as failed, not errored, when the build completes but tests have failed
When a test has failed, it should be marked as such. Currently, tests are marked as  `errored`, even when they complete their build.

Errored should only happen if no test data is available for report, i.e. a build step reports something like `Exit Code: 1`

### PR DESCRIPTION
**Pull request by paradox460**
This allows github to report 3 states, Success, Failure, and Error.

Previously, only Success and Error were reported.

This should resolve #77

Its the first Java I've written in half a decade, so hopefully it looks and works ok

Thanks!

### CODE REVIEW

**Comment by jonnyzzz** [comment]
Does it works for you?

**Comment by paradox460** [comment]
It doesn't appear to. Sorry about that.

Like I said, I haven't written Java in half a decade, and my skills were never very good with it at all, unfortunately. Hopefully you can see what I was trying to do and manage to implement it.

If you do, thats awesome. If not, I understand

Thanks.

**Comment by paradox460** [comment]
Doesn't actually work right, but we're getting there. Right now it reports error for any build :(

**Comment by jonnyzzz** [comment]
Thank you for the next attempt. I still believe the code will not compile. It should not be too complicated to try the build. Currently the plugin uses IntelliJ project model. 

I'll try to take a look to your changes from IntelliJ to make it workable.

**Comment by paradox460** [comment]
@iguanajazz was able to get it to compile, and gave me an archive to stick on our server. It "worked", in that it didn't crash, but didn't work in that it sent the wrong statuses to github.

We'll take another look at it later today and hopefully have something actually working by then :D

**Comment by paradox460** [comment]
I've got it working, and I'm currently using it on my server, with no adverse effects. It compiles properly now too

**Comment by jonnyzzz** [comment]
Thanks!

**Comment by jonnyzzz** [comment]
Thanks! I'll check it and merge!

**Comment by jonnyzzz** [comment]
I checked and merge the fix. Thank you once more for it! The next build will include it

**Pull request merged**
